### ISSUE TITLE
Property 'structuredClone' doesn't exist

### ISSUE THREAD

**Issue by devasidmi** [supabase/supabase-js#1504]
## Describe the bug

When attempting Apple sign‑in in an Expo app using `@supabase/supabase-js@2.51.0`, the client throws a runtime `ReferenceError: Property 'structuredClone' doesn't exist`. This error occurs regardless of JS engine (Hermes or JSC) and blocks native authentication flows that rely on `structuredClone`.

## To Reproduce

1. In a fresh Expo SDK 53 project, install Supabase JS at v2.51.0:

   ```bash
   npm install @supabase/supabase-js@2.51.0
   ```

2. Configure `jsEngine` to either Hermes or JSC in `app.json`.

3. Use this minimal repro code:

   ```js
   import * as AppleAuthentication from 'expo-apple-authentication';
   import { supabase } from './supabaseClient';

   export async function signInWithApple() {
     try {
       const credential = await AppleAuthentication.signInAsync({
         requestedScopes: [
           AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
           AppleAuthentication.AppleAuthenticationScope.EMAIL,
         ],
       });

       if (!credential.identityToken) {
         throw new Error('No identityToken returned from Apple.');
       }

       const { error, data: { user } } = await supabase.auth.signInWithIdToken({
         provider: 'apple',
         token: credential.identityToken,
       });

       if (error) {
         console.error('Supabase auth error:', error);
       } else {
         console.log('✓ Signed in:', user);
       }
     } catch (e: any) {
       if (e.code === 'ERR_REQUEST_CANCELED') {
         console.log('User cancelled Apple sign‑in');
       } else {
         console.error(e);
       }
     }
   }
   ```

4. Run the app and attempt Apple sign‑in.

5. Observe the Metro console error:

   ```
   ReferenceError: Property 'structuredClone' doesn't exist
   ```

   The app crashes before completing the flow.

## Expected behavior

Native sign‑in flows should work without requiring a global `structuredClone`. The client should either polyfill it on unsupported engines or avoid relying on it entirely. Behavior should match v2.50.5, where Apple sign‑in works under Expo.

## Screenshots

n/a — error is shown in Metro/console and app terminates.

## System information

* **Expo SDK:** 53 (React Native 0.79.5)
* **JS Engine:** Hermes (also reproduces on JSC)
* **Version of `@supabase/supabase-js`:** 2.51.0
* **Version of Node.js:** 18.16.0
* **Library for Apple auth:** `expo-apple-authentication@7.2.4`

## Additional context

* Downgrading to `@supabase/supabase-js@2.50.5` resolves the issue: Apple sign‑in completes successfully under Expo when using v2.50.5.
* A fix has been proposed in Expo’s PR [[#37503](https://github.com/expo/expo/pull/37503)](https://github.com/expo/expo/pull/37503), which would add a `structuredClone` polyfill for native apps. That PR is still open, all CI checks are passing, but it’s awaiting at least one approving review and resolution of a few reviewer concerns (stringification logic and transfer semantics) before merge.
* Once merged—or if Supabase JS bundles its own fallback—the Apple sign‑in error should be resolved. Let me know if you need further logs, test results under Hermes, or any adjustments to the proposed implementation.

**Comment by AF-appointhq** [comment]
I’m experiencing the same issue with email login in React Native CLI while using version 0.80.1. Has anyone found a solution that doesn’t involve downgrading the Supabase version?

**Comment by junghoonshin3** [comment]
Expo SDK: 53(React Native 0.79.5)
@supabase/supabase-js: 2.51.0
Node.js : 22.17.1

I'm encountering the error Property 'structuredClone' doesn't exist even when attempting to log in with Kakao or Google.

Downgrading the supabase-js version was not a viable solution for me.

Due to this issue, I'm having difficulty making progress on my project.
Is there any workaround or temporary solution available that I could use in the meantime?


Just adding this snippet to _layout.tsx or index.tsx works as a quick fix.
Fingers crossed the PR gets merged soon.



`if (typeof global.structuredClone === "undefined") {
  global.structuredClone = (value) => JSON.parse(JSON.stringify(value));
}`

**Comment by Chriztiaan** [comment]
Also encountering this issue for a fresh expo app using the latest version Supabase.

**Comment by AkilUnik** [comment]
"@supabase/supabase-js": "2.50.0", use this version

**Comment by thrcrt** [comment]
Same here!

**Comment by andyto** [comment]
Manage to solve it by polyfill structured-clone with https://github.com/ungap/structured-clone  in `App.tsx`
```
import structuredClone from "@ungap/structured-clone";
if (!("structuredClone" in global)) {
  global.structuredClone = structuredClone;
}
```

**Comment by e20249898** [comment]
> "@supabase/supabase-js": "2.50.0", use this version

it worked thx!!!!

**Comment by j4crev** [comment]
Thanks for reporting this. The auth team is now aware of the issue. I don't have a timeline for resolution.

**Comment by miraclenonso** [comment]
i am facing same issue

**Comment by miraclenonso** [comment]
> "@supabase/supabase-js": "2.50.0", use this version

it didnt work for me

**Comment by miraclenonso** [comment]
@cemalkilic please I don't really understand

**Comment by SalvatoreCampagnese** [comment]
I got the same issue, even logging with otp gives the error.

**Comment by SalvatoreCampagnese** [comment]
Even with #1507 still same problem happen.

**Comment by cemalkilic** [comment]
> Even with [#1507](https://github.com/supabase/supabase-js/pull/1507) still same problem happen.

Did you try with supabase-js version `2.52.0` ?

**Comment by miraclenonso** [comment]
@cemalkilic let me try that out...I pray it works.

**Comment by SalvatoreCampagnese** [comment]
It seems to be working now with version 2.52.0! Thank you @cemalkilic ❤️

**Comment by cemalkilic** [comment]
Hey all,
We've fixed the issue in the latest version of the `supabase-js` library.

You can use `"@supabase/supabase-js": "2.52.0"`

edit: Thanks @devasidmi for the very detailed report!

**Comment by bakerfugu** [comment]
Error is still occurring for me on `2.52.0`

Adding 
```
if (typeof global.structuredClone === "undefined") { global.structuredClone = (value) => JSON.parse(JSON.stringify(value)); }
```

To my `index.js` fixes it.

**Comment by miraclenonso** [comment]
@bakerfugu the package itself is supposed to resolve the issue 🤦 what line of code did you add that file in your index.js please.

**Comment by j4crev** [comment]
> Error is still occurring for me on `2.52.0`
> 
> Adding 
> ```
> if (typeof global.structuredClone === "undefined") { global.structuredClone = (value) => JSON.parse(JSON.stringify(value)); }
> ```
> 
> To my `index.js` fixes it.

I'm not sure why 2.52.0 would still be giving you issues. They fixed it with the same parse/stringify code you used - just created a function for it, and are using that instead of structuredClone.
