### ISSUE TITLE
Types for join involving Computed Relationships do not work

### ISSUE THREAD

**Issue by hmnd** [supabase/supabase-js#1641]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Resolving joins on [Computed Relationships](https://docs.postgrest.org/en/stable/references/api/resource_embedding.html#computed-relationships) in types broke somewhere between v1.16.3 and v1.17.7, resulting in an error like: `SelectQueryError<"could not find the relation between placement and hotel">`.

## To Reproduce

See `src/supabase.test-d.ts` in the `working` and `broken` branches of my repro repo: https://github.com/hmnd/postgrest-computed-rels-repro

## Expected behavior

Computed Relationship is resolved successfully.

**Comment by avallete** [comment]
This should now be fixed in the latest `2.75.1` version see: https://github.com/orgs/supabase/discussions/39773

Please let me know if you have any more error, and feel free to re-open.

**Comment by jdgamble555** [comment]
@avallete - I'm still getting this issue:
```
const { error, data } = await supabase
    .from('courses')
    .select(`
        id,
        ...,
        all_languages(
            code,
            name
        )
    `)
    .eq('id', id)
    .single()
    .overrideTypes<{
        all_languages: {
            code: string;
            name: string
        }[]
    }>();
```
My `schema` has this...
```sql
CREATE OR REPLACE FUNCTION public.all_languages(courses)
RETURNS SETOF public.languages
LANGUAGE sql
SET search_path = ''
AS $$
    ... some sql here
$$;
```

But when I remove the overRideTypes, I see this:

<img width="955" height="420" alt="Image" src="https://github.com/user-attachments/assets/ba0da5bc-dc54-467f-8d83-b877d1d7b00b" />

Clearly, it works without the typing. I'm using `v2.77.0`

J

**Comment by avallete** [comment]
Hi @jdgamble555,

Did you regenerate your types with latest cli version ? The new inference require both the new types generation from `postgrest-meta` and the latest version of the `supabase-js`.

If you still have the issue, would you mind to create a MRE using this template: https://github.com/avallete/supabase-js-types-mre-boilerplate

So I can investigate better what's going on.

**Comment by jdgamble555** [comment]
Yup, I forgot to regenerate the types, duhhh 😅!

All of my complex types now work! Thanks you!

I am having a problem with counting though:
```sql
CREATE OR REPLACE FUNCTION public.user_count(comments)
RETURNS bigint
LANGUAGE sql
SET search_path = ''
AS $$
  SELECT COUNT(*)
  FROM public.comments WHERE comments.user_id = auth.uid();
$$;
```
This returns `number | null` instead of just `number`... that, I think, is only thing left 🤞

You can view my repo:

https://github.com/jdgamble555/supabase-types

J
