### ISSUE TITLE
`throwOnError` with await returns nullable type

### ISSUE THREAD

**Issue by dogukanakkaya** [supabase/supabase-js#801]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

`.throwOnError` should return non-nullable type because since in a case of error it will throw instead of returning an `error` object with null `data` object.

## To Reproduce

See below code for example:
```ts
const { data, error } = await supabase.from('groups').insert({ name }).select('id').throwOnError().single()
```

In this example return type is nullabe `{ data: { id: string } } | null` but it shouldn't because it'll throw on error.

In this case I have to do below to correct typing which doesn't make any sense to do extra if checks even though it's unnecessary:
```ts
const { data, error } = await supabase.from('groups').insert({ name }).select('id').throwOnError().single()

if (error) throw error
```

## Expected behavior

If `.throwOnError` called return type must be `{ data: NonNullable<...>, error: null }` or even without error object if possible.

## Screenshots
<img width="888" alt="Screenshot 2023-06-29 at 12 47 37" src="https://github.com/supabase/supabase-js/assets/51231605/0bd9b545-03a8-444c-97c8-c3871c3a8b5a">

## System information

- OS: MacOS
- Version of supabase-js: 2.26.0
- Version of Node.js: 20.3.1
- Version of Typescript: 5.1.3

**Comment by dogukanakkaya** [comment]
An update here: seems like `.then` is not returning correct typing as await which was expected since both are resolving promises. I missed `PostgrestSingleResponse` generic. It also has `data` as nullable, so bug exists in both cases.

**Comment by gualcasas** [comment]
Thank you for opening this issue. I was about to open an issue for this exact thing.

**Comment by rfreydi** [comment]
One workaround until it's resolved:

```typescript
async get(id: string) {
    const entity = await this.supabase.client.from('auth.users').select(`*`)
      .eq('id', id)
      .single()
      .throwOnError();

    return entity.data as NonNullable<typeof entity.data>;
  }
```

**Comment by rfreydi** [comment]
One workaround until it's resolved:

```typescript
const get = async (id: string) => {
  const entity = await supabase.client.from('auth.users').select(`*`)
    .eq('id', id)
    .single()
    .throwOnError();

  return entity.data as NonNullable<typeof entity.data>;
}
```

**Comment by mmkal** [comment]
I opened a PR to support this: https://github.com/supabase/postgrest-js/pull/494

I got impatient so I published it under [@rebundled/postgrest-js](https://www.npmjs.com/package/@rebundled/postgrest-js). Here's how you can use it with `@supabase/ssr`:

```bash
npm install @rebundled/postgrest-js
```

```ts
import { CookieOptions, createServerClient } from '@supabase/ssr'
import { PostgrestClient } from '@rebundled/postgrest-js'
import { cookies } from 'next/headers'
import { Database } from '~/db'

export const createClient = () => {
  const client = createServerClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
      },
    },
  )

  // @ts-expect-error `.rest` is protected
  const { rest } = client
  const wrapper = new PostgrestClient<T>(rest.url, {
    fetch: rest.fetch,
    headers: rest.headers,
    schema: rest.schemaName,
  }).throwOnError()
  return Object.assign(wrapper, {
    rest,
    realtime: client.realtime,
    auth: client.auth,
  })
}
```

You can then use like:

```ts
import {createClient} from '..'

export default async () => {
  const client = createClient()

  const { data: user } = await client.from('users').select('*').single()

  console.log(`Hello ${user.username}`) // no need to check truthiness/ throw manually
}
```

If you need access to the non-throwing client, you can use `createClient().rest`. Note that if the PR is merged, it'll probably make sense to make a change in this repo too, so explicitly creating a `new PostgrestClient` wouldn't be necessary. But this seemed like a non-invasive way to let people try this out now.

**Comment by AlbertMarashi** [comment]
+1. this is kinda annoying tbh

**Comment by ThatGuySam** [comment]
Would changing the functionality of `.throwOnError()` break existing apps that depend on null to represent that the data wasn't found, for example with `.single().throwOnError()`?

One alternative could just be more chainable throw methods, such as: 
```js
throwOnEmpty()
throwOnFalsy()
throwOn( function(){} )
```

**Comment by AlbertMarashi** [comment]
I don't see why it would be backwards compatible to return non-nullable when returning an array of items. `maybeSingle` should stay nullable, and `single` should be non-nullable

**Comment by yatoogamii** [comment]
Any update on this feature ?

**Comment by yuxinqi-chan** [comment]
another workaround only get data
```
const data = await supabase
    .from("table")
    .select()
    .throwOnError()
    .then((res) => !res.error && res.data);
```

**Comment by gurumaxi** [comment]
Any update on this feature?

**Comment by soedirgo** [comment]
Resolved in https://github.com/supabase/supabase-js/pull/1355

**Comment by duncannz** [comment]
It seems like the fix only works when using `await`; when using `.then()`, `throwOnError()` seems to still incorrectly add `null` to the return type.

Perhaps it has something to do with the custom implementation of `.then()` that takes `onfulfilled` and `onrejected` as two arguments rather than allowing `.catch()` to be chained?
